require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ContentfulTest' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ContentfulTestTests' do
    inherit! :complete
    # Pods for testing
  end
  
  use_frameworks!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #  use_flipper!({ 'Flipper' => '0.74.0' })
  #  post_install do |installer|
  #    flipper_post_install(installer)
  #  end
end

target 'ContentfulTest-tvOS' do
  # Pods for ContentfulTest-tvOS

  target 'ContentfulTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'ContentfulTest-WidgetExtension' do
  use_frameworks!
  pod 'Contentful'
end
